# 🐳 Православный портал - Docker Compose Production
version: '2.2'

services:
  # 🗄️ PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pravoslavie_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: pravoslavie_portal_db
      POSTGRES_USER: pravoslavie_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - pravoslavie_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pravoslavie_user -d pravoslavie_portal_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🚀 Redis Cache
  redis:
    image: redis:7-alpine
    container_name: pravoslavie_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - pravoslavie_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 🌐 Django Web Application
  web:
    build: .
    container_name: pravoslavie_web
    restart: unless-stopped
    volumes:
      - media_files:/app/media
      - static_files:/app/staticfiles
      - ./logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
      - DATABASE_URL=postgresql://pravoslavie_user:${POSTGRES_PASSWORD}@postgres:5432/pravoslavie_portal_db
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - pravoslavie_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🔄 Celery Worker (для фоновых задач)
  celery:
    build: .
    container_name: pravoslavie_celery
    restart: unless-stopped
    command: celery -A config worker -l info
    volumes:
      - media_files:/app/media
      - ./logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
      - DATABASE_URL=postgresql://pravoslavie_user:${POSTGRES_PASSWORD}@postgres:5432/pravoslavie_portal_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - pravoslavie_network

  # 📊 Celery Beat (для периодических задач)
  celery-beat:
    build: .
    container_name: pravoslavie_celery_beat
    restart: unless-stopped
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
      - DATABASE_URL=postgresql://pravoslavie_user:${POSTGRES_PASSWORD}@postgres:5432/pravoslavie_portal_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - pravoslavie_network

  # 🌍 Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    container_name: pravoslavie_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - static_files:/app/staticfiles:ro
      - media_files:/app/media:ro
      - ./docker/ssl:/etc/ssl/certs:ro
    depends_on:
      - web
    networks:
      - pravoslavie_network

  # 📈 Monitoring (опционально)
  watchtower:
    image: containrrr/watchtower
    container_name: pravoslavie_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
    networks:
      - pravoslavie_network

# 💾 Постоянные тома
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  media_files:
    driver: local
  static_files:
    driver: local

# 🌐 Сеть
networks:
  pravoslavie_network:
    driver: bridge
