# 🐳 Православный портал - Docker Compose Development
version: '2.2'

services:
  # 🗄️ PostgreSQL Database (Development)
  postgres:
    image: postgres:15-alpine
    container_name: pravoslavie_postgres_dev
    restart: unless-stopped
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: pravoslavie_local_db
      POSTGRES_USER: pravoslavie_user
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - pravoslavie_network_dev

  # 🚀 Redis Cache (Development)
  redis:
    image: redis:7-alpine
    container_name: pravoslavie_redis_dev
    restart: unless-stopped
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - pravoslavie_network_dev

  # 🌐 Django Web Application (Development)
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: pravoslavie_web_dev
    restart: unless-stopped
    volumes:
      - .:/app
      - media_files_dev:/app/media
      - static_files_dev:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_dev
      - DATABASE_URL=postgresql://pravoslavie_user:dev_password_123@postgres:5432/pravoslavie_local_db
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=True
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    networks:
      - pravoslavie_network_dev
    command: python manage.py runserver 0.0.0.0:8000

  # 📧 MailHog (Email Testing)
  mailhog:
    image: mailhog/mailhog
    container_name: pravoslavie_mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP
    networks:
      - pravoslavie_network_dev

  # 🔍 PostgreSQL Admin (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pravoslavie_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pravoslavie-portal.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - pravoslavie_network_dev
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin

# 💾 Development Volumes
volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local
  media_files_dev:
    driver: local
  static_files_dev:
    driver: local
  pgadmin_data_dev:
    driver: local

# 🌐 Development Network
networks:
  pravoslavie_network_dev:
    driver: bridge
