# Generated by Django 4.2.7 on 2025-06-15 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Краткое описание категории', verbose_name='Описание')),
                ('content_type', models.CharField(choices=[('story', 'Видео-рассказы'), ('book', 'Книги'), ('article', 'Статьи'), ('audio', 'Аудио'), ('product', 'Товары'), ('general', 'Общее')], default='general', max_length=20, verbose_name='Тип контента')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap иконка, например: bi-book', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#6c5ce7', help_text='HEX код цвета для категории', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(choices=[('general', 'Общие вопросы'), ('technical', 'Технические проблемы'), ('content', 'Предложения по контенту'), ('subscription', 'Вопросы по подписке'), ('cooperation', 'Сотрудничество')], max_length=20, verbose_name='Тема')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('answered', 'Отвечено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Православный портал', max_length=100, verbose_name='Название сайта')),
                ('site_description', models.TextField(default='Духовные рассказы, книги и аудио для современного человека', verbose_name='Описание сайта')),
                ('contact_email', models.EmailField(default='info@pravoslavie-portal.ru', max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(default='+7 (800) 123-45-67', max_length=20, verbose_name='Контактный телефон')),
                ('social_telegram', models.URLField(blank=True, verbose_name='Telegram канал')),
                ('social_youtube', models.URLField(blank=True, verbose_name='YouTube канал')),
                ('social_vk', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Режим обслуживания')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Сообщение в режиме обслуживания')),
                ('analytics_yandex', models.CharField(blank=True, max_length=20, verbose_name='Yandex.Metrika ID')),
                ('analytics_google', models.CharField(blank=True, max_length=20, verbose_name='Google Analytics ID')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Тег')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='URL-адрес')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('color', models.CharField(default='#74b9ff', max_length=7, verbose_name='Цвет тега')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
    ]
