# Generated by Django 4.2.7 on 2025-08-13 01:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('feedback_type', models.CharField(choices=[('bug', 'Нашёл ошибку'), ('feature', 'Предложить улучшение'), ('design', 'Дизайн и интерфейс'), ('content', 'Контент и материалы'), ('performance', 'Скорость работы'), ('other', 'Другое')], max_length=20, verbose_name='Тип обращения')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('url', models.URLField(blank=True, verbose_name='URL страницы')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('screen_resolution', models.CharField(blank=True, max_length=20, verbose_name='Разрешение экрана')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мобильная обратная связь',
                'verbose_name_plural': 'Мобильная обратная связь',
                'ordering': ['-created_at'],
            },
        ),
    ]
