# Generated by Django 4.2.7 on 2025-09-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_address_work_hours_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='audio_coming_soon',
            field=models.BooleanField(default=True, verbose_name='Аудио: показать "Скоро"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='books_coming_soon',
            field=models.BooleanField(default=False, verbose_name='Библиотека: показать "Скоро"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fairy_tales_coming_soon',
            field=models.BooleanField(default=True, verbose_name='Сказки: показать "Скоро"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shop_coming_soon',
            field=models.BooleanField(default=False, verbose_name='Магазин: показать "Скоро"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_audio',
            field=models.BooleanField(default=False, verbose_name='Показывать "Аудио"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_books',
            field=models.BooleanField(default=True, verbose_name='Показывать "Библиотеку"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_fairy_tales',
            field=models.BooleanField(default=False, verbose_name='Показывать "Сказки"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_shop',
            field=models.BooleanField(default=True, verbose_name='Показывать "Магазин"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_stories',
            field=models.BooleanField(default=True, verbose_name='Показывать "Видео-рассказы"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stories_coming_soon',
            field=models.BooleanField(default=False, verbose_name='Рассказы: показать "Скоро"'),
        ),
    ]
