# Generated by Django 4.2.7 on 2025-06-20 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('preferred_age_group', models.CharField(blank=True, max_length=10)),
                ('interested_categories', models.JSONField(default=list)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_purchase_intents', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.DurationField(blank=True, null=True)),
                ('purchase_probability', models.FloatField(default=0.0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_user_behavior',
            },
        ),
        migrations.CreateModel(
            name='PopularContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('purchase_intents', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('trending_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'analytics_popular_content',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('notify_payment_launch', models.BooleanField(default=True)),
                ('notify_new_content', models.BooleanField(default=True)),
                ('notify_discounts', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('source_page', models.URLField(help_text='Страница, где подписался')),
                ('interested_in', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_email_subscription',
            },
        ),
        migrations.CreateModel(
            name='PurchaseIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Для анонимных пользователей', max_length=40)),
                ('content_type', models.CharField(choices=[('book', 'Книга'), ('fairy_tale', 'Сказка'), ('subscription', 'Подписка'), ('audio', 'Аудио')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('button_type', models.CharField(choices=[('buy', 'Купить'), ('download', 'Скачать'), ('subscribe', 'Подписаться'), ('listen', 'Слушать'), ('read_full', 'Читать полностью')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referer', models.URLField(blank=True)),
                ('page_url', models.URLField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.PositiveIntegerField(default=1)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_purchase_intent',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='analytics_p_content_7c591c_idx'), models.Index(fields=['clicked_at'], name='analytics_p_clicked_99cbe6_idx'), models.Index(fields=['user'], name='analytics_p_user_id_7fe547_idx'), models.Index(fields=['session_key'], name='analytics_p_session_925e86_idx')],
            },
        ),
    ]
