# Generated by Django 4.2.7 on 2025-06-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsubscription',
            options={'verbose_name': 'Email подписка', 'verbose_name_plural': 'Email подписки'},
        ),
        migrations.AlterModelOptions(
            name='popularcontent',
            options={'verbose_name': 'Популярный контент', 'verbose_name_plural': 'Популярный контент'},
        ),
        migrations.AlterModelOptions(
            name='purchaseintent',
            options={'verbose_name': 'Намерение покупки', 'verbose_name_plural': 'Намерения покупки'},
        ),
        migrations.AlterModelOptions(
            name='userbehavior',
            options={'verbose_name': 'Поведение пользователя', 'verbose_name_plural': 'Поведение пользователей'},
        ),
    ]
