# Generated by Django 4.2.7 on 2025-06-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_emailsubscription_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseintent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='purchaseintent',
            name='country',
        ),
        migrations.AddField(
            model_name='emailsubscription',
            name='emails_sent',
            field=models.PositiveIntegerField(default=0, verbose_name='Отправлено email'),
        ),
        migrations.AddField(
            model_name='emailsubscription',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний email'),
        ),
        migrations.AddField(
            model_name='emailsubscription',
            name='notify_weekly_reports',
            field=models.BooleanField(default=False, verbose_name='Получать недельные отчеты'),
        ),
        migrations.AddField(
            model_name='purchaseintent',
            name='admin_notified',
            field=models.BooleanField(default=False, verbose_name='Админ уведомлен'),
        ),
        migrations.AddField(
            model_name='purchaseintent',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Уведомление отправлено'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='notify_discounts',
            field=models.BooleanField(default=False, verbose_name='Уведомлять о скидках'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='notify_new_content',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о новом контенте'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='notify_payment_launch',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о запуске платежей'),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('week_end', models.DateField(verbose_name='Конец недели')),
                ('total_purchase_intents', models.PositiveIntegerField(default=0, verbose_name='Общее количество кликов')),
                ('unique_users', models.PositiveIntegerField(default=0, verbose_name='Уникальные пользователи')),
                ('new_subscriptions', models.PositiveIntegerField(default=0, verbose_name='Новые подписки')),
                ('top_content', models.JSONField(default=list, verbose_name='Популярный контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('sent_to_admins', models.BooleanField(default=False, verbose_name='Отправлен админам')),
                ('sent_to_subscribers', models.BooleanField(default=False, verbose_name='Отправлен подписчикам')),
            ],
            options={
                'verbose_name': 'Недельный отчет',
                'verbose_name_plural': 'Недельные отчеты',
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
    ]
