# Generated by Django 4.2.7 on 2025-08-02 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0003_remove_purchaseintent_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('step', models.CharField(choices=[('visit', 'Посещение'), ('view_product', 'Просмотр товара'), ('add_to_cart', 'Добавление в корзину'), ('checkout_start', 'Начало оформления'), ('purchase', 'Покупка')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('product_type', models.CharField(blank=True, max_length=20)),
                ('traffic_source', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Воронка конверсии',
                'verbose_name_plural': 'Воронка конверсии',
                'unique_together': {('date', 'step', 'product_type')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Просмотр страницы'), ('purchase', 'Покупка'), ('purchase_complete', 'Завершенная покупка'), ('add_to_cart', 'Добавление в корзину'), ('download', 'Скачивание'), ('interaction', 'Взаимодействие'), ('search', 'Поиск'), ('session_end', 'Конец сессии'), ('time_on_page', 'Время на странице'), ('form_submission', 'Отправка формы'), ('error', 'Ошибка')], max_length=20)),
                ('session_id', models.CharField(db_index=True, max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('page_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие аналитики',
                'verbose_name_plural': 'События аналитики',
                'db_table': 'analytics_event',
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='analytics_e_event_t_676ab6_idx'), models.Index(fields=['session_id', 'timestamp'], name='analytics_e_session_a53a9b_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_e_user_id_2b59cd_idx')],
            },
        ),
    ]
