# Generated by Django 4.2.7 on 2025-06-20 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookreview',
            name='unique_book_user_review',
        ),
        migrations.RemoveConstraint(
            model_name='userfavoritebook',
            name='unique_user_favorite_book',
        ),
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together={('book', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritebook',
            unique_together={('user', 'book')},
        ),
    ]
