# Generated by Django 4.2.7 on 2025-06-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_bookreview_unique_book_user_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Отзыв'),
        ),
    ]
