# Generated by Django 4.2.7 on 2025-07-27 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_alter_bookreview_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=1, verbose_name='Текущая страница')),
                ('total_pages_read', models.PositiveIntegerField(default=0, verbose_name='Всего страниц прочитано')),
                ('reading_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Прогресс чтения (%)')),
                ('reading_time', models.PositiveIntegerField(default=0, verbose_name='Время чтения (минуты)')),
                ('bookmarks', models.JSONField(blank=True, default=list, verbose_name='Закладки')),
                ('notes', models.JSONField(blank=True, default=list, verbose_name='Заметки')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='Последнее чтение')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия чтения',
                'verbose_name_plural': 'Сессии чтения',
                'ordering': ['-last_read_at'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название главы')),
                ('content', models.TextField(verbose_name='Содержание главы')),
                ('chapter_number', models.PositiveIntegerField(verbose_name='Номер главы')),
                ('start_page', models.PositiveIntegerField(default=1, verbose_name='Начальная страница')),
                ('end_page', models.PositiveIntegerField(default=1, verbose_name='Конечная страница')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Глава книги',
                'verbose_name_plural': 'Главы книг',
                'ordering': ['book', 'chapter_number'],
                'unique_together': {('book', 'chapter_number')},
            },
        ),
    ]
