# Generated by Django 4.2.7 on 2025-07-27 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_bookreadingsession_bookchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(verbose_name='Страница')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=1, verbose_name='Текущая страница')),
                ('total_pages', models.PositiveIntegerField(default=1, verbose_name='Всего страниц')),
                ('reading_time', models.PositiveIntegerField(default=0, verbose_name='Время чтения (минуты)')),
                ('last_read', models.DateTimeField(auto_now=True, verbose_name='Последнее чтение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('font_size', models.FloatField(default=1.1, verbose_name='Размер шрифта')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('sepia', 'Сепия')], default='light', max_length=20, verbose_name='Тема')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия чтения',
                'verbose_name_plural': 'Сессии чтения',
                'ordering': ['-last_read'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.AlterModelOptions(
            name='bookchapter',
            options={'ordering': ['order'], 'verbose_name': 'Глава книги', 'verbose_name_plural': 'Главы книг'},
        ),
        migrations.RenameField(
            model_name='bookchapter',
            old_name='end_page',
            new_name='page_end',
        ),
        migrations.RenameField(
            model_name='bookchapter',
            old_name='start_page',
            new_name='page_start',
        ),
        migrations.AlterUniqueTogether(
            name='bookchapter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.DeleteModel(
            name='BookReadingSession',
        ),
        migrations.AddField(
            model_name='readingbookmark',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.readingsession', verbose_name='Сессия чтения'),
        ),
        migrations.RemoveField(
            model_name='bookchapter',
            name='chapter_number',
        ),
        migrations.RemoveField(
            model_name='bookchapter',
            name='created_at',
        ),
    ]
