# Generated by Django 4.2.7 on 2025-06-30 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Максимум 1000 символов', verbose_name='Текст комментария')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('dislikes_count', models.PositiveIntegerField(default=0, verbose_name='Дизлайки')),
                ('replies_count', models.PositiveIntegerField(default=0, verbose_name='Ответы')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплен')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='stories.storycomment', verbose_name='Родительский комментарий')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.story', verbose_name='Рассказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Спам'), ('hate', 'Разжигание ненависти'), ('harassment', 'Притеснение'), ('violence', 'Насилие'), ('inappropriate', 'Неподходящий контент'), ('other', 'Другое')], max_length=20, verbose_name='Причина жалобы')),
                ('description', models.TextField(blank=True, verbose_name='Дополнительное описание')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Рассмотрена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stories.storycomment', verbose_name='Комментарий')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Жалобщик')),
            ],
            options={
                'verbose_name': 'Жалоба на комментарий',
                'verbose_name_plural': 'Жалобы на комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Лайк'), ('dislike', 'Дизлайк')], max_length=10, verbose_name='Тип реакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='stories.storycomment', verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на комментарий',
                'verbose_name_plural': 'Реакции на комментарии',
            },
        ),
        migrations.AddIndex(
            model_name='storycomment',
            index=models.Index(fields=['story', '-created_at'], name='stories_sto_story_i_434dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='storycomment',
            index=models.Index(fields=['user', '-created_at'], name='stories_sto_user_id_c60bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='storycomment',
            index=models.Index(fields=['parent'], name='stories_sto_parent__68f168_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentreport',
            unique_together={('comment', 'reporter')},
        ),
        migrations.AddIndex(
            model_name='commentreaction',
            index=models.Index(fields=['comment', 'reaction_type'], name='stories_com_comment_599e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreaction',
            index=models.Index(fields=['user', '-created_at'], name='stories_com_user_id_6a7648_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('comment', 'user')},
        ),
    ]
