# Generated by Django 4.2.7 on 2025-07-03 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0002_storycomment_commentreport_commentreaction_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='storyview',
            name='stories_sto_story_i_8c4de9_idx',
        ),
        migrations.RemoveIndex(
            model_name='storyview',
            name='stories_sto_story_i_37fd27_idx',
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together={('story', 'user', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['story', '-last_viewed'], name='stories_sto_story_i_7a58d9_idx'),
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['user', '-last_viewed'], name='stories_sto_user_id_8966d8_idx'),
        ),
    ]
