# Generated by Django 4.2.7 on 2025-07-04 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0005_searchquery_storylike_userrecommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylistPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay_enabled', models.BooleanField(default=True, verbose_name='Автовоспроизведение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorites_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites_users', to='stories.playlist', verbose_name="Плейлист 'Избранное'")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_preferences', to=settings.AUTH_USER_MODEL)),
                ('watch_later_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_later_users', to='stories.playlist', verbose_name="Плейлист 'Посмотреть позже'")),
            ],
            options={
                'verbose_name': 'Настройки плейлистов пользователя',
                'verbose_name_plural': 'Настройки плейлистов пользователей',
            },
        ),
    ]
