# Generated by Django 4.2.7 on 2025-08-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_userplaylistpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Изображение-превью для видео', null=True, upload_to='stories/thumbnails/', verbose_name='Превью изображение'),
        ),
    ]
