# Generated by Django 4.2.7 on 2025-08-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_story_thumbnail'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['is_published', 'is_featured', '-created_at'], name='stories_sto_is_publ_eb23c2_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['category', '-views_count'], name='stories_sto_categor_4ef270_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-views_count'], name='stories_sto_views_c_b38edf_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['slug'], name='stories_sto_slug_b9091c_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['youtube_embed_id'], name='stories_sto_youtube_af70aa_idx'),
        ),
    ]
