# Generated by Django 4.2.7 on 2025-08-19 23:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pwa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bedtime_stories', '🌙 Сказки на ночь'), ('orthodox_calendar', '⛪ Православный календарь'), ('new_content', '📚 Новый контент'), ('fairy_tales', '🧚 Терапевтические сказки'), ('audio_content', '🎵 Аудио-контент'), ('book_releases', '📖 Новые книги'), ('special_events', '🎉 Особые события'), ('daily_wisdom', '💭 Мудрость дня')], max_length=50, unique=True, verbose_name='Категория')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='🔔', max_length=10, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('default_enabled', models.BooleanField(default=False, verbose_name='Включена по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория уведомлений',
                'verbose_name_plural': 'Категории уведомлений',
            },
        ),
        migrations.AlterModelOptions(
            name='offlineaction',
            options={'verbose_name': 'Офлайн действие', 'verbose_name_plural': 'Офлайн действия'},
        ),
        migrations.AlterModelOptions(
            name='pwaanalytics',
            options={'verbose_name': 'PWA аналитика', 'verbose_name_plural': 'PWA аналитика'},
        ),
        migrations.AlterModelOptions(
            name='pwainstallevent',
            options={'verbose_name': 'Событие установки PWA', 'verbose_name_plural': 'События установки PWA'},
        ),
        migrations.AlterUniqueTogether(
            name='cachedcontent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='offlineaction',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='pwaanalytics',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='pwaanalytics',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='pwainstallevent',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='cachedcontent',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cachedcontent',
            name='cache_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cachedcontent',
            name='cache_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cachedcontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='cachedcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cachedcontent',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cachedcontent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offlineaction',
            name='action_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='offlineaction',
            name='action_type',
            field=models.CharField(choices=[('create_playlist', 'Создание плейлиста'), ('add_to_playlist', 'Добавление в плейлист'), ('toggle_favorite', 'Изменение избранного'), ('add_to_cart', 'Добавление в корзину'), ('remove_from_cart', 'Удаление из корзины')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offlineaction',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='offlineaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offlineaction',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offlineaction',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='offlineaction',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offlineaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth_key',
            field=models.TextField(verbose_name='Auth ключ'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.URLField(verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh_key',
            field=models.TextField(verbose_name='P256DH ключ'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='pwaanalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pwaanalytics',
            name='event_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pwaanalytics',
            name='event_type',
            field=models.CharField(choices=[('install', 'Установка'), ('uninstall', 'Удаление'), ('offline_usage', 'Использование офлайн'), ('sync_performed', 'Синхронизация'), ('notification_sent', 'Уведомление отправлено'), ('notification_clicked', 'Уведомление кликнуто')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pwaanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pwainstallevent',
            name='browser',
            field=models.CharField(max_length=50, verbose_name='Браузер'),
        ),
        migrations.AlterField(
            model_name='pwainstallevent',
            name='installed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pwainstallevent',
            name='platform',
            field=models.CharField(max_length=50, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='pwainstallevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pwainstallevent',
            name='user_agent',
            field=models.TextField(verbose_name='User Agent'),
        ),
        migrations.AlterUniqueTogether(
            name='cachedcontent',
            unique_together={('user', 'cache_key')},
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('quiet_hours_enabled', models.BooleanField(default=True, verbose_name='Тихие часы')),
                ('quiet_start', models.TimeField(default='22:00', verbose_name='Начало тихих часов')),
                ('quiet_end', models.TimeField(default='08:00', verbose_name='Конец тихих часов')),
                ('notify_monday', models.BooleanField(default=True)),
                ('notify_tuesday', models.BooleanField(default=True)),
                ('notify_wednesday', models.BooleanField(default=True)),
                ('notify_thursday', models.BooleanField(default=True)),
                ('notify_friday', models.BooleanField(default=True)),
                ('notify_saturday', models.BooleanField(default=True)),
                ('notify_sunday', models.BooleanField(default=True)),
                ('child_mode', models.BooleanField(default=False, verbose_name='Детский режим')),
                ('child_bedtime', models.TimeField(default='20:00', verbose_name='Время сказки')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений пользователя',
                'verbose_name_plural': 'Настройки уведомлений пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включена')),
                ('frequency', models.CharField(choices=[('immediately', 'Сразу'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('custom', 'Настраиваемая')], default='daily', max_length=20, verbose_name='Частота')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='Предпочитаемое время')),
                ('max_daily_count', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Максимум в день')),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Приоритет (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwa.notificationcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка на уведомления',
                'verbose_name_plural': 'Подписки на уведомления',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
