# Generated by Django 4.2.7 on 2025-08-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwa', '0002_notificationcategory_alter_offlineaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrthodoxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('great_feast', 'Великий праздник'), ('major_feast', 'Большой праздник'), ('minor_feast', 'Малый праздник'), ('fast', 'Пост'), ('fast_day', 'Постный день'), ('memorial', 'Поминовение'), ('saint', 'День святого'), ('icon', 'Икона')], max_length=20, verbose_name='Тип события')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('day', models.IntegerField(verbose_name='День')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год (если конкретный)')),
                ('is_old_style', models.BooleanField(default=False, verbose_name='По старому стилю')),
                ('is_movable', models.BooleanField(default=False, verbose_name='Переходящий праздник')),
                ('easter_offset', models.IntegerField(blank=True, null=True, verbose_name='Сдвиг от Пасхи (дни)')),
                ('icon_url', models.URLField(blank=True, verbose_name='Ссылка на икону')),
                ('reading_url', models.URLField(blank=True, verbose_name='Ссылка на чтения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Православное событие',
                'verbose_name_plural': 'Православные события',
                'ordering': ['month', 'day'],
            },
        ),
    ]
