# Generated by Django 4.2.7 on 2025-08-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwa', '0003_orthodoxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrthodoxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('day', models.IntegerField(verbose_name='День')),
                ('fasting_type', models.CharField(choices=[('no_fast', 'Поста нет'), ('light_fast', 'Обычный пост'), ('strict_fast', 'Строгий пост'), ('dry_eating', 'Сухоядение'), ('with_oil', 'Пост с маслом'), ('with_fish', 'Можно рыбу'), ('wine_oil', 'Вино и масло'), ('complete_fast', 'Полное воздержание')], default='no_fast', max_length=20, verbose_name='Тип поста')),
                ('fasting_description', models.TextField(blank=True, verbose_name='Описание поста')),
                ('allowed_food', models.TextField(blank=True, verbose_name='Что можно есть')),
                ('spiritual_note', models.TextField(blank=True, verbose_name='Духовное наставление')),
                ('gospel_reading', models.TextField(blank=True, verbose_name='Евангельское чтение')),
                ('epistle_reading', models.TextField(blank=True, verbose_name='Апостольское чтение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ежедневная православная информация',
                'verbose_name_plural': 'Ежедневная православная информация',
                'ordering': ['month', 'day'],
                'unique_together': {('month', 'day')},
            },
        ),
    ]
