# Generated by Django 4.2.7 on 2025-08-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwa', '0004_dailyorthodoxinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('great_lent', 'Великий пост'), ('christmas_fast', 'Рождественский пост'), ('assumption_fast', 'Успенский пост'), ('peter_paul_fast', 'Петров пост'), ('apostles_fast', 'Апостольский пост'), ('weekly_fast', 'Еженедельный пост (ср/пт)'), ('one_day_fast', 'Однодневный пост')], max_length=50, verbose_name='Название')),
                ('title', models.CharField(max_length=100, verbose_name='Отображаемое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_month', models.IntegerField(blank=True, null=True, verbose_name='Месяц начала')),
                ('start_day', models.IntegerField(blank=True, null=True, verbose_name='День начала')),
                ('end_month', models.IntegerField(blank=True, null=True, verbose_name='Месяц окончания')),
                ('end_day', models.IntegerField(blank=True, null=True, verbose_name='День окончания')),
                ('easter_start_offset', models.IntegerField(blank=True, help_text='Отрицательные значения - до Пасхи, положительные - после', null=True, verbose_name='Начало от Пасхи (дни)')),
                ('easter_end_offset', models.IntegerField(blank=True, null=True, verbose_name='Конец от Пасхи (дни)')),
                ('fasting_rules', models.JSONField(default=dict, help_text='Правила по дням недели в формате JSON', verbose_name='Правила поста')),
                ('priority', models.IntegerField(default=1, help_text='Для разрешения конфликтов между постами', verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Период поста',
                'verbose_name_plural': 'Периоды постов',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='orthodoxevent',
            name='event_type',
            field=models.CharField(choices=[('great_feast', 'Великий праздник'), ('major_feast', 'Большой праздник'), ('minor_feast', 'Малый праздник'), ('fast_start', 'Начало поста'), ('fast_end', 'Окончание поста'), ('special_day', 'Особый день'), ('memorial', 'Поминовение'), ('saint', 'День святого'), ('icon', 'Икона')], max_length=20, verbose_name='Тип события'),
        ),
    ]
