# Generated by Django 4.2.7 on 2025-08-03 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Рекомендуемый размер: 200x200 пикселей', null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, help_text='Расскажите немного о себе', max_length=500, verbose_name='О себе')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('', 'Не указан')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('favorite_saints', models.CharField(blank=True, help_text='Например: св. Николай Чудотворец, св. Сергий Радонежский', max_length=200, verbose_name='Любимые святые')),
                ('confession_frequency', models.CharField(blank=True, help_text='Например: раз в месяц, по большим праздникам', max_length=50, verbose_name='Частота исповеди')),
                ('favorite_prayers', models.TextField(blank=True, max_length=300, verbose_name='Любимые молитвы')),
                ('parish', models.CharField(blank=True, help_text='Храм, который вы посещаете', max_length=150, verbose_name='Приход')),
                ('email_notifications', models.CharField(choices=[('all', 'Все уведомления'), ('important', 'Только важные'), ('none', 'Отключить')], default='important', max_length=20, verbose_name='Email уведомления')),
                ('newsletter_subscription', models.BooleanField(default=True, verbose_name='Подписка на рассылку')),
                ('new_content_notifications', models.BooleanField(default=True, verbose_name='Уведомления о новом контенте')),
                ('order_notifications', models.BooleanField(default=True, verbose_name='Уведомления о заказах')),
                ('preferred_font_size', models.FloatField(default=1.0, help_text='От 0.8 до 2.0', verbose_name='Размер шрифта')),
                ('preferred_theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('sepia', 'Сепия')], default='light', max_length=20, verbose_name='Тема оформления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
