# Generated by Django 4.2.7 on 2025-06-19 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_product',
        ),
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_user_product_purchase',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='include_audio',
            field=models.BooleanField(default=False, verbose_name='Включить озвучку'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='include_illustrations',
            field=models.BooleanField(default=False, verbose_name='Включить иллюстрации'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='personalization_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные персонализации'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='Особые пожелания'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='fairy_tales/audio/%Y/%m/', verbose_name='Аудио-файл'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемое завершение'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fairy_tale_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('ready', 'Готова'), ('delivered', 'Доставлена')], max_length=20, verbose_name='Статус сказки'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='generated_content',
            field=models.TextField(blank=True, verbose_name='Готовая сказка'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='illustration_file',
            field=models.FileField(blank=True, null=True, upload_to='fairy_tales/illustrations/%Y/%m/', verbose_name='Иллюстрации'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='include_audio',
            field=models.BooleanField(default=False, verbose_name='Включить озвучку'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='include_illustrations',
            field=models.BooleanField(default=False, verbose_name='Включить иллюстрации'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='personalization_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные персонализации'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='Особые пожелания'),
        ),
        migrations.AddField(
            model_name='product',
            name='audio_option_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена озвучки'),
        ),
        migrations.AddField(
            model_name='product',
            name='fairy_tale_template_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID шаблона сказки'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_audio_option',
            field=models.BooleanField(default=False, verbose_name='Доступна озвучка'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_illustration_option',
            field=models.BooleanField(default=False, verbose_name='Доступны иллюстрации'),
        ),
        migrations.AddField(
            model_name='product',
            name='illustration_option_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена иллюстраций'),
        ),
        migrations.AddField(
            model_name='product',
            name='personalization_form_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфигурация формы персонализации'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_personalization',
            field=models.BooleanField(default=False, verbose_name='Требует персонализации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('book', 'Книга'), ('audio', 'Аудио'), ('subscription', 'Подписка'), ('fairy_tale', 'Персонализированная сказка')], max_length=20, verbose_name='Тип товара'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'product')},
        ),
    ]
