# Generated by Django 4.2.7 on 2025-08-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_cartitem_unique_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее скачивание'),
        ),
    ]
