# Generated by Django 4.2.7 on 2025-08-17 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_add_discount_fields_manual'),
    ]

    operations = [
    ]
