# Generated by Django 4.2.7 on 2025-08-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_20250817_0521'),
    ]

    operations = [
    ]
