# Generated by Django 4.2.7 on 2025-08-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_merge_20250817_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_discount_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Примененный промокод'),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Промокод'),
        ),
    ]
