# Generated by Django 4.2.7 on 2025-06-16 23:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FairyTaleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(help_text='Краткое описание целей и задач категории', verbose_name='Описание категории')),
                ('age_group', models.CharField(choices=[('child', 'Дети (3-12 лет)'), ('teen', 'Подростки (13-17 лет)'), ('adult', 'Взрослые (18+ лет)'), ('family', 'Семейные (все возрасты)')], default='child', max_length=20, verbose_name='Возрастная группа')),
                ('icon', models.CharField(default='magic', help_text='Bootstrap иконка, например: bi-magic', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#9b59b6', help_text='HEX код цвета', max_length=7, verbose_name='Цвет категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория сказок',
                'verbose_name_plural': 'Категории сказок',
                'ordering': ['age_group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FairyTaleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название сказки')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL-адрес')),
                ('short_description', models.CharField(help_text='Описание для каталога', max_length=300, verbose_name='Краткое описание')),
                ('therapeutic_goals', models.JSONField(default=list, help_text='Список целей из TherapeuticGoal', verbose_name='Терапевтические цели')),
                ('content_template', models.TextField(help_text='Текст с переменными: {name}, {age}, {problem}, {hobby} и др.', verbose_name='Шаблон сказки')),
                ('personalization_fields', models.JSONField(default=dict, help_text='Настройки форм для персонализации', verbose_name='Поля персонализации')),
                ('target_age_min', models.PositiveIntegerField(default=3, verbose_name='Минимальный возраст')),
                ('target_age_max', models.PositiveIntegerField(default=12, verbose_name='Максимальный возраст')),
                ('is_free', models.BooleanField(default=True, verbose_name='Бесплатная сказка')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Базовая цена персонализации')),
                ('has_audio_option', models.BooleanField(default=False, verbose_name='Доступна озвучка')),
                ('audio_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена озвучки')),
                ('has_illustration_option', models.BooleanField(default=False, verbose_name='Доступны иллюстрации')),
                ('illustration_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена иллюстраций')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор сказки')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='fairy_tales.fairytalecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Шаблон сказки',
                'verbose_name_plural': 'Шаблоны сказок',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID заказа')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email заказчика')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон заказчика')),
                ('personalization_data', models.JSONField(default=dict, help_text='Все данные, введенные клиентом', verbose_name='Данные персонализации')),
                ('include_audio', models.BooleanField(default=False, verbose_name='Включить озвучку')),
                ('include_illustrations', models.BooleanField(default=False, verbose_name='Включить иллюстрации')),
                ('special_requests', models.TextField(blank=True, verbose_name='Особые пожелания')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базовая цена')),
                ('audio_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена озвучки')),
                ('illustration_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена иллюстраций')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('in_progress', 'В работе'), ('ready', 'Готов'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('estimated_completion', models.DateTimeField(blank=True, null=True, verbose_name='Планируемое завершение')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('generated_content', models.TextField(blank=True, verbose_name='Готовая сказка')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='fairy_tales/audio/%Y/%m/', verbose_name='Аудио-файл')),
                ('illustration_file', models.FileField(blank=True, null=True, upload_to='fairy_tales/illustrations/%Y/%m/', verbose_name='Файл с иллюстрациями')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fairy_tales.fairytaletemplate', verbose_name='Шаблон сказки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fairy_tale_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ персонализации',
                'verbose_name_plural': 'Заказы персонализации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FairyTaleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 звезд'), (2, '2 звезд'), (3, '3 звезд'), (4, '4 звезд'), (5, '5 звезд')], verbose_name='Оценка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок отзыва')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Текст отзыва')),
                ('helped_with_problem', models.BooleanField(blank=True, null=True, verbose_name='Помогла ли сказка с проблемой?')),
                ('child_liked', models.BooleanField(blank=True, null=True, verbose_name='Понравилась ли ребенку?')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Рекомендует другим')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый отзыв')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairy_tale_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='fairy_tales.personalizationorder', verbose_name='Заказ')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fairy_tales.fairytaletemplate', verbose_name='Шаблон сказки')),
            ],
            options={
                'verbose_name': 'Отзыв о сказке',
                'verbose_name_plural': 'Отзывы о сказках',
                'ordering': ['-created_at'],
                'unique_together': {('template', 'author')},
            },
        ),
        migrations.CreateModel(
            name='FairyTaleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='fairy_tales.fairytaletemplate', verbose_name='Шаблон сказки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_fairy_tales', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранная сказка',
                'verbose_name_plural': 'Избранные сказки',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'template')},
            },
        ),
    ]
