# Generated by Django 4.2.7 on 2025-06-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairy_tales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairytaletemplate',
            name='personalization_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Настройки форм для персонализации', verbose_name='Поля персонализации'),
        ),
        migrations.AlterField(
            model_name='fairytaletemplate',
            name='therapeutic_goals',
            field=models.JSONField(blank=True, default=list, help_text='Список целей из TherapeuticGoal', verbose_name='Терапевтические цели'),
        ),
    ]
