# Generated by Django 4.2.7 on 2025-06-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairy_tales', '0002_alter_fairytaletemplate_personalization_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairytaletemplate',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 400x250 пикселей', null=True, upload_to='fairy_tales/covers/%Y/%m/', verbose_name='Обложка сказки'),
        ),
    ]
